### PR TITLE
Blocks 0.0.1

### PR DESCRIPTION
**Pull request by rizar**
See the subject.

@bartvm , do you know what else should be changed to switch to the two-branch system?

### CODE REVIEW

**Comment by rizar** [comment]
Cool, Travis and Coveralls seems to work. Bart, can you add the "stable" branch to Scrutinizer? Seems like it has to be done from some control panel there.

**Comment by bartvm** [comment]
Enabled on Scrutinizer.

**Comment by bartvm** [comment]
By the way, could you make this PR to the master branch? There's not reason to make it to `stable`.

**Comment by rizar** [comment]
Scrutinizer was triggered.

Do you want me to commit these changes to master and then to create a new stable branch? Or to merge them in both?

**Comment by bartvm** [comment]
Either is fine by me, as long as the commits end up in `master`, else the branches will have diverged before we even started :p

**Comment by rizar** [comment]
By the way, should we move to mila-udem?

**Comment by bartvm** [comment]
I guess this weekend is as good as any.

**Comment by vdumoulin** [comment]
+1 for the move to @mila-udem, we should also do that for Fuel. We just need to make sure that the mailing lists are notified of the change.

**Comment by rizar** [comment]
I guess I will wait until the migration is done, merge it into master and create a stable branch once again.

**Comment by rizar** [comment]
Closed in favour of #641

**Pull request closed without merging**
