### PR TITLE
Arguments for SimpleRecurrent should be required

### PR DESCRIPTION
**Pull request by rizar**
See #817

### CODE REVIEW

**Comment by ASalvail** [comment]
If you intend to make the `states` mandatory, the docstrings of `SimpleRecurrent` and `LSTM`  (at the very least) will need to be changed. Furthermore, the docs of the RNN won't run anymore (see the very first block of code) and will need to be modified.

**Comment by rizar** [comment]
I looked at the docs and it is not said there that the parameters are optional. Moreover, for `GatedRecurrent` and `LSTM` the states are already mandatory. And the tests  pass just fine, including doctests.

Perhaps I should clarify that the states are mandatory only for `iterate=False`. Does this help?

**Comment by ASalvail** [comment]
> Perhaps I should clarify that the states are mandatory only for iterate=False. Does this help?

Indeed, I thought you wanted to make them mandatory for all `apply` calls since this is what the patch of the PR is doing by removing the default argument of `state`.

**Comment by ASalvail** [comment]
AFAIK, this piece of code in the docs on recurrent bricks would fail with this patch on the `rnn.apply(x)`.

```python
>>> import numpy
>>> import theano
>>> from theano import tensor
>>> from blocks import initialization
>>> from blocks.bricks import Identity
>>> from blocks.bricks.recurrent import SimpleRecurrent
>>> x = tensor.tensor3('x')
>>> rnn = SimpleRecurrent(
...     dim=3, activation=Identity(), weights_init=initialization.Identity())
>>> rnn.initialize()
>>> h = rnn.apply(x)
>>> f = theano.function([x], h)
>>> print(f(numpy.ones((3, 1, 3), dtype=theano.config.floatX))) 
```

Are the doctests testing these too?

**Comment by rizar** [comment]
I tried the piece of code you suggested and it did not fail, because the behaviour when `iterate=True` is not changed by this PR.

**Comment by ASalvail** [comment]
Ah, my bad. I just learned how decorator works. Since the recurrent 
decorator provides the default values, it all turns out to work.

Thanks for the info!

**Pull request merged**
