### PR TITLE
AggregationSchemes for Maximum and Minimum.

### LINKED ISSUE #129: More Aggregation Schemes: Min, Max, Concatenate
That would a nice exercise for a newcomer: to add a couple of new aggregation schemes in addition to existing ones. Would be very helpful for debugging purposes.

### PR DESCRIPTION
**Pull request by dwf**
~~Surprised to find these didn't already exist.~~ Fixes #129.

### CODE REVIEW

**Comment by dmitriy-serdyuk** [comment]
It is issue #129 .

**Comment by dwf** [comment]
So it is.

**Comment by dwf** [comment]
I added a Concatenate scheme for completeness.

**Comment by dmitriy-serdyuk** [comment]
Sorry, forgot about this PR. It looks good. I have one question: do you think that concatenate aggregator should always create an extra dim? For example, in your test `[4, 12, 7, 5]` should be `[[4, 5], [7, 5]]`.

**Comment by dwf** [comment]
That would make things simpler wouldn't it? Changed in 7e8a556.

**Comment by dmitriy-serdyuk** [comment]
Cool, LGTM.

**Pull request merged**
