### PR TITLE
Fix failing test after merging a PR in Fuel

### PR DESCRIPTION
**Pull request by vdumoulin**
I don't know why Travis showed the Blocks tests as passing in the Fuel PR, but here we are...

### CODE REVIEW

**Comment by vdumoulin** [comment]
Alright... the failing tests cascaded to `blocks-examples`. I'll make a PR for that as well.

**Comment by bartvm** [comment]
It's because of the comment I made here: https://github.com/mila-udem/fuel/pull/156#issuecomment-110393345

Currently, the Blocks tests on the Fuel repo are actually run with the Fuel `master` branch i.e. they're not being tested at all. We need to move the Fuel installation command to *before* the Blocks installation command, otherwise pip just installs Fuel's `master` branch, and when the Fuel installation command is called later, pip just says "already installed".

**Comment by vdumoulin** [comment]
I'll make a PR to change that, thanks!

**Comment by vdumoulin** [comment]
@bartvm It appears MNIST isn't being properly downloaded by Blocks.

I had a look at the corresponding line in `.travis.yml` and I think there's a problem with it:

``` bash
curl -O https://raw.githubusercontent.com/bartvm/fuel/master/.travis-data.sh | bash -s -- mnist
```

should probably be

``` bash
curl https://raw.githubusercontent.com/bartvm/fuel/master/.travis-data.sh | bash -s -- mnist
```

as I think `curl -O` will write to a file without outputing anything to the stdout.

Also, should we switch from `bartvm/fuel/master` to `mila-udem/fuel/master`?

**Comment by bartvm** [comment]
Yes to both :)

**Comment by vdumoulin** [comment]
Tests pass, and the changes are trivial, I'll go ahead and merge.

**Pull request merged**
