### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by bartvm**

### CODE REVIEW

**Comment by rizar** [comment]
I am lost. Why updating dependencies fixes Blocks builds but does not help for Fuel?

**Comment by bartvm** [comment]
Merge this one and https://github.com/mila-udem/fuel/pull/237 simultaneously, and everything should work :)

**Comment by bartvm** [comment]
Fuel is fixed with https://github.com/mila-udem/fuel/pull/237, but it's status is failing because it runs the tests on Blocks master, which are broken, and will only be fixed after merging this

**Comment by rizar** [comment]
OK, let's try!

**Pull request merged**
