### PR TITLE
Added a Softplus brick.

### PR DESCRIPTION
**Pull request by ASalvail**
This brick only interfaces with the softplus function from theano.

### CODE REVIEW

**Comment by rizar** [comment]
A paper reference in the docs and a test added to `tests/bricks/test_bricks.py:test_activations` would be appreciated. Except that, looks good!

**Comment by ASalvail** [comment]
Forgot the test. Will do.
As for the paper, I have no idea who invented it.

**Comment by rizar** [comment]
[this paper](http://machinelearning.wustl.edu/mlpapers/paper_files/AISTATS2011_GlorotBB11.pdf) cites some other paper as the softplus origin, I guess we should follow the example.

**Comment by rizar** [comment]
Sorry for failing tests, it is because of https://github.com/mila-udem/blocks-examples/issues/34

**Comment by ASalvail** [comment]
Alright, I added the reference and test, plus some bonus tests for the Softmax and Logistic bricks.

**Comment by ASalvail** [comment]
Is test coverage computed according to the test functions name? If it is, I could split the `test_activations` in 5 separate methods.

**Comment by ASalvail** [comment]
Isn't the doc overwritten by `ActivationDocumentation`? If so, how do you propose the referenced paper should be added?

**Comment by rizar** [comment]
You are right, unfortunately it is. For now, let's leave it as is.

**Comment by rizar** [comment]
Sorry for delay, forgot about this PR.

**Pull request merged**
