### PR TITLE
Environment variable to set config.temp_dir

### PR DESCRIPTION
**Pull request by rizar**

### CODE REVIEW

**Comment by dwf** [comment]
I don't understand the failure. Apparently `enum34` is getting pulled in somehow but I don't see why it would, and I can't reproduce locally.

**Comment by rizar** [comment]
@bartvm ,  we are having troubles with Travis and conda. Could you please take a look?

**Comment by bartvm** [comment]
I had a look yesterday, but I am as baffled as @dwf, I can't find a reference to `enum34` anywhere, so I have no idea why it is being pulled in.

**Comment by dwf** [comment]
Are Travis instances 32-bit Linux? That's the only thing I can think of
explaining the fact that I don't see it on linux64.

**Comment by bartvm** [comment]
No, they're 64 bit: `OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"`

**Comment by bartvm** [comment]
Just noticed: This error occurs when updating the default miniconda installation i.e. it's happening on Python 2.7. It's only after updating Miniconda that we installed Python 3.4 in a virtual environment:

```
[0K$ conda update -q --yes conda
Fetching package metadata: ....
Solving package specifications: ...............
Package plan for installation in environment /home/travis/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          502 B
    openssl-1.0.2j             |                0         3.2 MB
    sqlite-3.13.0              |                0         4.0 MB
    zlib-1.2.8                 |                3         101 KB
    python-2.7.12              |                1        12.1 MB
    enum34-1.1.6               |           py27_0          53 KB
    pycosat-0.6.1              |           py27_1         190 KB
    requests-2.11.1            |           py27_0         621 KB
    ruamel_yaml-0.11.14        |           py27_0         352 KB
    setuptools-27.2.0          |           py27_0         521 KB
    wheel-0.29.0               |           py27_0          81 KB
    conda-4.2.9                |           py27_0         360 KB
    pip-8.1.2                  |           py27_0         1.5 MB
    ------------------------------------------------------------
                                           Total:        23.0 MB

The following NEW packages will be INSTALLED:

    enum34:      1.1.6-py27_0  
    ruamel_yaml: 0.11.14-py27_0

The following packages will be UPDATED:

    conda:       3.19.0-py27_0 --> 4.2.9-py27_0  
    conda-env:   2.4.5-py27_0  --> 2.6.0-0       
    openssl:     1.0.2d-0      --> 1.0.2j-0      
    pip:         7.1.2-py27_0  --> 8.1.2-py27_0  
    pycosat:     0.6.1-py27_0  --> 0.6.1-py27_1  
    python:      2.7.11-0      --> 2.7.12-1      
    requests:    2.9.0-py27_0  --> 2.11.1-py27_0 
    setuptools:  18.8.1-py27_0 --> 27.2.0-py27_0 
    sqlite:      3.8.4.1-1     --> 3.13.0-0      
    wheel:       0.26.0-py27_1 --> 0.29.0-py27_0 
    zlib:        1.2.8-0       --> 1.2.8-3       


travis_time:end:02cad74c:start=1476284540459578015,finish=1476284549667664230,duration=9208086215
[0Ktravis_fold:end:before_install.6
[0Ktravis_fold:start:before_install.7
[0Ktravis_time:start:07481c82
[0K$ export FUEL_DATA_PATH=$TRAVIS_BUILD_DIR/data

travis_time:end:07481c82:start=1476284549672108548,finish=1476284549675459066,duration=3350518
[0Ktravis_fold:end:before_install.7
[0Ktravis_fold:start:install.1
[0Ktravis_time:start:1a7a252d
[0K$ conda --debug install -q --yes python=$TRAVIS_PYTHON_VERSION --file req-travis-conda.txt
Fetching package metadata .......
Solving package specifications: ....
UnsatisfiableError: The following specifications were found to be in conflict:
  - coverage ==4.2
  - enum34 -> python 2.6*|2.7*|3.3*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by bartvm** [comment]
That was badly phrased, but what I meant: Maybe Conda is installing `enum34` in the default environment (which is Python 2.7) and then refuses to install Python 3.4 because of it? Seems like an Anaconda bug in that case.

**Comment by dmitriy-serdyuk** [comment]
In this case, an easy fix would be to download Miniconda3-latest for Python 3 tests.

**Comment by dwf** [comment]
@rizar can you rebase so the tests run with the updated Travis config?

**Comment by rizar** [comment]
Done!

**Comment by rizar** [comment]
Can I merge?

**Comment by dwf** [comment]
Sure.

**Pull request merged**
