### PR TITLE
Remove --allow-external

### PR DESCRIPTION
**Pull request by dmitriy-serdyuk**
For mila-udem/fuel#405

@nouiz

### CODE REVIEW

**Comment by dmitriy-serdyuk** [comment]
Fixed

**Comment by nouiz** [comment]
2 CI still fail. I think a new version of pep8 is used. That caused a failure in Fuel

**Comment by dmitriy-serdyuk** [comment]
Ok, I figured out the problem. Virtualenv puts a bunch of its things into `bin` directory. Scrutinizer crashes on those files.

**Comment by dmitriy-serdyuk** [comment]
@nouiz I give up. I was tinkering for quite a while. I fixed Travis and Scrutinizer tests. But I have no idea what happens to Scrutinizer analysis.

**Comment by nouiz** [comment]
So, what do we do? As the tests passed, we could merge. This would fix possible security issue, so I would go in that direction.

**Comment by dmitriy-serdyuk** [comment]
OK, let me cleanup history then

**Pull request merged**
