### PR TITLE
Allow to pass kwargs to scan

### LINKED ISSUE #1046: truncate_gradient should be argument to theano.scan
It seems like blocks should have the functionality to truncate gradients for BPTT in RNN.

I think this line should be edited.
https://github.com/mila-udem/blocks/blob/0e1696d39d9c73e93f63cba5d0b4f75ecce07dfb/blocks/bricks/recurrent.py#L223 

Discussion
https://groups.google.com/forum/#!topic/blocks-users/g25REC5ackQ

### PR DESCRIPTION
**Pull request by dmitriy-serdyuk**
Fixes #1046

### CODE REVIEW

**Comment by dwf** [comment]
Great, should we add a simple test? (Although frankly I don't know how you would go about testing this.)

**Comment by dmitriy-serdyuk** [comment]
Exactly...

I can separate `theano.scan` call and substitute it with a mock call in a test. Should I do it?

**Comment by dwf** [comment]
SGTM

**Comment by dmitriy-serdyuk** [comment]
And there's a problem with travis again, I cannot see its icon at all.

**Comment by dmitriy-serdyuk** [comment]
I run tests locally and everything ok.

**Pull request merged**
