### PR TITLE
Make Convolutional{Activation,Layer,Sequence} honour use_bias

### LINKED ISSUE #847: ConvolutionalActivation, ConvolutionalSequence do not honor use_bias=False
ConvolutionalActivation does not push use_bias to its Convolutional child, nor does ConvolutionalSequence:

    import theano.tensor as T

    from blocks.bricks import conv, Rectifier
    from blocks import initialization, graph

    cnn = conv.ConvolutionalSequence([
        conv.ConvolutionalActivation(
            activation=Rectifier().apply,
            filter_size=(1, 1),
            num_filters=1,
            use_bias=False)
        for _ in xrange(3)],
        num_channels=1, image_size=(1, 1),
        use_bias=False,
        weights_init=initialization.IsotropicGaussian(1e-3),
        biases_init=initialization.Constant(0))
    cnn.initialize()

    x = T.tensor4()
    y = cnn.apply(x)

    print graph.ComputationGraph(y).parameters

Removing biases (e.g. for batch normalization) requires reaching into internals.

### PR DESCRIPTION
**Pull request by dwf**
Fixes #847 (which I had said was a CCW ticket but turned out to be a little bit involved).

@cooijmanstim Can you give this a look?

@dmitriy-serdyuk You too? Should be quick.

### CODE REVIEW

**Comment by cooijmanstim** [comment]
Sorry, I see now that I posted my comment on the issue rather than here on the pull request. Looks good to me, thanks!

**Comment by dwf** [comment]
Thanks, I'd like another person with merge rights to sign off on it before I hit the big green button, but it should be in soon.

**Comment by dwf** [comment]
By the way, is this useful/critical for #851? The ticket seemed to sound like it.

**Comment by cooijmanstim** [comment]
No, I intend to touch that PR again this weekend. It's an "interesting" complication though, that users will still have to worry about redundant biases (which may not be redundant depending on tied_bias settings).

**Comment by dwf** [comment]
Okay, that's kinda why I tackled it (and because I was digging around in that code anyway with #873). But glad to know it isn't a blocker.

**Comment by rizar** [comment]
Hey there, I saw recently a proposal to add `_push_allocation_config` to `Initializable` which would handle `use_bias` option. Is there a particular reason why you do no go this way?

Alternatively, what if we just let go of `use_bias`? It is not that much harm to have `biases_ini` propagated to bricks that do not have biases.

**Comment by dwf** [comment]
@rizar I made that proposal at the same time I was doing this, because
ultimately that's a more elegant solution. I think that is probably the
right direction in the long term, but in the short term this fixes what is
clearly a bug in the simplest way possible. We should not let the perfect
be the enemy of the good.

**Comment by rizar** [comment]
I agree that fixing things makes sense. But let me go through all recent bias-related issues for the record:

https://github.com/mila-udem/blocks/issues/847 - `use_bias` is forgotten in the list of the settings pushed downward in `ConvolutionalLayer`, the code sort of relies on it be pushed by `Initializable` but `Initializable` does not do that.

https://github.com/mila-udem/blocks/issues/789 - `use_bias` is often never mentioned in the docstring of the bricks that actually support this option, e.g. `Linear`

https://github.com/mila-udem/blocks/issues/697 - it might be not very to get why `Initializable` brick have both `use_bias` and `has_biases`

So it seems they all have a single reason behind: `use_bias` is declared in `Initializable`, but it is the actual brick where it is handled. I find this strange and I think we should remove `use_bias` from `Initializable` and only have it in the bricks that actually have biases. If you agree with that, I will create an issue.

**Comment by dwf** [comment]
@rizar Maybe a simple way to handle this, presuming basically every brick that has a bias has it on by default anyway:

```python
class HasBias(object):
    @property
    def use_bias(self):
        return getattr(self, '_use_bias', True)

    @use_bias.setter
    def use_bias(self, value):
        self._use_bias = value
```

Inherit from this mixin in every brick that should have a bias.

**Comment by rizar** [comment]
Your code example misses a constructor, and having a constructor means that
also an additional super call will be necessary. Which makes me wonder if
having it as a mixin is better then simply add the related code to every
class. Perhaps it is, because this is a way to declare the interface.

**Comment by dwf** [comment]
Just to be clear, as written, it doesn't actually need a constructor.

**Comment by rizar** [comment]
Okay, but assuming `Linear` inherits from `HasBias`, will it accept
`use_bias=False` as a constructor parameter?

**Comment by dwf** [comment]
I see what you're saying now. Yes, for that we'd need to either add it to
every class or else add a constructor and add it to the chain of super()
calls.

**Comment by rizar** [comment]
Right. But as I said before, maybe it does make sense to have it as a mixin
so that all classes that have biases definitely had the same interface.

**Pull request merged**
