### PR TITLE
Release 0.1.1

### PR DESCRIPTION
**Pull request by rizar**
This hotfix release is mainly necessary because of the mess with the version number, but in addition a few documentation changes sneak into the stable, which I think is fine.

### CODE REVIEW

**Comment by dmitriy-serdyuk** [comment]
Requirements should link the stable branch of fuel.

**Comment by rizar** [comment]
But they do link the stable branch now, and this pull request does not change this. Do you agree?

**Comment by dmitriy-serdyuk** [comment]
Ok, the checklist:

- Make changes in `master`:
  - [ ] Freeze other PRs
  - [ ] Increase the counter
- Create a pull request to merge `master` into `stable`, maybe one has to use a proxy branch 
  which diverts from `stable`, merges `master` into it.
  - [ ] Create a pull request to Fuel
  - [ ] Check the Travis CI build, make sure it refers the stable branch
  - [ ] Check the Theano version
  - [ ] Check referred Fuel version
  - [ ] Merge Fuel pull request
  - [ ] Merge this pull request
- After the PR is merged:
  - [ ] Create release
  - [ ] Check documentation build
  - [ ] Double check that the version corresponds `__version__`

Did I forget something? Feel free to copy the list and modify it.

**Comment by rizar** [comment]
The checklist looks nice, but some items should be explained in a bit more detail. For instance, we have to refer to the stable branch of Fuel and to the latest Theano revision which is known not to have bugs. Would be great to have this checklist in the documentation. Meanwhile, should I merge this?

**Comment by dmitriy-serdyuk** [comment]
I see no issues now, LGTM.

**Pull request merged**
