### PR TITLE
WIP: New Serialization

### PR DESCRIPTION
**Pull request by rizar**
The current serialization used in Blocks has the following shortcomings:

- although the parameters are indeed saved robustly as numpy arrays, they are contained in a zip file with a lot of rubbish, which makes it in practice not possible to fetch them

- only parameters are saved as additional fields in the dump, for all the rest one can only use `save_separately` which is less convenient, since it produces separate files, #746 

- if main loop is itself not picklable, nothing will be saved, #758 

This PR proposes a new serialization, which does not have these issues. It is so far only a working draft, but I put some effort into docstring of the new `blocks/serialization.py` module and kindly invite you to read it and tell, if you like it and if you think that this PR should be finished and merged.

TODO:
- [ ]  documentation is missing for many functions
- [ ] handle usual shared variables (not created by bricks)
- [ ]  handle shared variables without names
- [ ]  handle variables with duplicate names 
- [ ]  support CUDA

### CODE REVIEW

**Comment by vdumoulin** [comment]
Does this also solve stack limit issues when retrieving parameters from a really deep theano graph?

**Comment by rizar** [comment]
Partially. That is the parameters will be always 100% saved without crash, period. But if you also pickle the whole thing, you will still get a crash. On the bright side, with this new serialization pickling the whole thing can be switched off.

**Comment by rizar** [comment]
@vdumoulin , I  updated the doctest to explain what I mean.

**Comment by vdumoulin** [comment]
Great, thanks!

**Comment by dmitriy-serdyuk** [comment]
Great work! Looks very good.

I'll look more carefully later. Some parameters can not be present in `model.parameters`, for example if they are not used in the training cost computation. As I can see, they are not going to be pickled with the persistent id.

**Comment by rizar** [comment]
>  Some parameters can not be present in model.parameters, for example if they are not used in the training cost computation.

I will find this situation rather unlikely, but I agree that there should be full control of what is being called parameters, and I plan to have at the following  levels: 

- `model.parameters` is mutable, that is the parameters set can be changed for all extensions at once

- `Checkpoint` should accept `parameters` keyword to directly control what is being saved

**Comment by rizar** [comment]
A note: make sure that it works without CUDA installed.

**Pull request closed without merging**
