### PR TITLE
added docstring for tied_biases

### PR DESCRIPTION
**Pull request by Tejas-Khot**
Solved issue #722

### CODE REVIEW

**Comment by Tejas-Khot** [comment]
@dwf @rizar I am a new contributor to blocks and this is my first PR. I verified wth `flake8` and `pep8` and it passed those tests offline. I cannot understand the Scrutinizer's `D504: Docstring exceeds 75 characters` error since the docstring for `num_channels` is actually longer than the one I added for `tied_biases`

Could you please help me understand how I can check for Scrutinizer and travis issues ? This is new to me so some help at the start will be very much helpful.

**Comment by dwf** [comment]
It's the actual *line* length it's complaining about, not the length of the section. The [docstring standard](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) we follow specifies 75 characters per line maximum in docstrings. So you'll need to rewrap.

**Comment by dwf** [comment]
Don't worry about the Travis failure, that looks unrelated (@rizar?).

**Comment by Tejas-Khot** [comment]
@dwf It seems solved...can be merged now

**Comment by dwf** [comment]
LGTM, thanks.

**Pull request merged**
