### PR TITLE
Override base path for temporary file creation

### PR DESCRIPTION
**Pull request by yingzha**

### CODE REVIEW

**Comment by yingzha** [comment]
@dwf , could you help me check my ticket if you have time? I didn't find where the problem is.

**Comment by dwf** [comment]
Weird, it looks like it's getting called with the string None rather than the value None. Just a second.

**Comment by dwf** [comment]
I do not understand why coverage dropped. That doesn't make a lot of sense, and the Coveralls interface is unhelpful in determining why...

**Comment by yingzha** [comment]
Did I do something wrong :-(

**Comment by dwf** [comment]
No I don't think so, the coverage checker is sometimes a little unreliable... I restarted Travis build.

**Comment by dwf** [comment]
Okay, 0.05% drop is not worth worrying about. It was like -1.4% before, weird.

I think we can merge, I just want @vdumoulin to review the code that _I_ wrote so that I am not accepting my own changes. :smile:

**Comment by yingzha** [comment]
:-) Thanks for your guide and sorry again for my several weeks delay.

**Comment by dwf** [comment]
@rizar @vdumoulin Since I have now contributed to this PR I shouldn't also be merging it without a second pair of eyes. Please merge at will if you think it's ready.

**Pull request merged**
