### PR TITLE
Fix log unpickling

### LINKED ISSUE #765: Unpickling resumed log fails
When unpickling a saved log that has previously been resumed using `resume()`, the following error is raised:

````python
In [1]: from blocks.serialization import load, dump
Using gpu device 0: NVS 4200M
In [2]: from blocks.log import TrainingLog
In [3]: log1 = TrainingLog()
In [4]: dump(log1, "log1.pkl")
In [5]: log2 = load("log1.pkl")
In [6]: dump(log2, "log2.pkl")
In [7]: load("log2.pkl")  # loading an unresumed log works
Out[7]: defaultdict(<type 'dict'>, {})
In [8]: log2.resume()
In [9]: dump(log2, "log3.pkl")
In [10]: load("log3.pkl")  # loading a resumed log does not work
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-a2b8b841ca66> in <module>()
----> 1 load("log3.pkl")

/home/fabian/msc/exp/env/lib/python2.7/site-packages/theano/misc/pkl_utils.pyc in load(f, persistent_load)
    318         p = pickle.Unpickler(BytesIO(zip_file.open('pkl').read()))
    319         p.persistent_load = persistent_load(zip_file)
--> 320         return p.load()
    321 
    322 

/home/fabian/msc/exp/local/lib/python2.7/pickle.pyc in load(self)
    856             while 1:
    857                 key = read(1)
--> 858                 dispatch[key](self)
    859         except _Stop, stopinst:
    860             return stopinst.value

/home/fabian/msc/exp/local/lib/python2.7/pickle.pyc in load_newobj(self)
   1081         args = self.stack.pop()
   1082         cls = self.stack[-1]
-> 1083         obj = cls.__new__(cls, *args)
   1084         self.stack[-1] = obj
   1085     dispatch[NEWOBJ] = load_newobj

TypeError: buffer() takes at least 1 argument (0 given)
````

This may be related to [Python bug 8323](http://bugs.python.org/issue8323) which is classified as `wontfix`.

### PR DESCRIPTION
**Pull request by dmitriy-serdyuk**
Fixes #765 .

### CODE REVIEW

**Comment by dmitriy-serdyuk** [comment]
Hmm, buffers are non-picklable but strings are non-sqliteable.

**Comment by dwf** [comment]
@dmitriy-serdyuk ¯\_(ツ)_/¯

`__setstate__` and `__getstate__` time?

**Comment by bartvm** [comment]
Just a quick note that this is what you're running into: http://bugs.python.org/issue8323 It's a bug in Python 2 that won't be fixed...

**Comment by dmitriy-serdyuk** [comment]
@bartvm  we still need a workaround since lots and lots of people are still using Python2.

**Comment by bartvm** [comment]
If you're going to store strings instead of binary data, don't forget to update the column preferences in the SQL commands e.g. https://github.com/mila-udem/blocks/blob/master/blocks/log/sqlite.py#L124 and https://github.com/mila-udem/blocks/blob/master/blocks/log/sqlite.py#L131

**Comment by dmitriy-serdyuk** [comment]
Actually, storing ids as text makes much more sense. I've never seen that id has a binary type, I guess, more sophisticated databases have optimizations for index build by a text field.

**Comment by dmitriy-serdyuk** [comment]
@dwf , can you take a look?

**Comment by dwf** [comment]
@dmitriy-serdyuk Sorry, somehow I missed your request. Looking now.

**Comment by dwf** [comment]
LGTM, the only thing I'm wondering is whether there are any backwards compatibility issues with existing SQLite files?

**Comment by dmitriy-serdyuk** [comment]
Most probably it's not backward compatible. I'll try to figure it out, but currently I cannot run sqlite backend at all. Seems I have too old sqlite3 library.

**Comment by dwf** [comment]
OK. We're pretty bold about API breakages but I'm not sure to what extent
we want to hang people's old log files out to dry. But if @bartvm gives it
his blessing (since he wrote this thing and is probably one of the few
using it) I'm happy to merge as is.

**Comment by dmitriy-serdyuk** [comment]
It may be compatible if sqlite can read binary data as text. In this case uuids will be different but still unique. From [here](https://www.sqlite.org/datatype3.html):

> SQLite uses a more general dynamic type system. In SQLite, the datatype of a value is associated with the value itself, not with its container. The dynamic type system of SQLite is backwards compatible with the more common static type systems of other database engines in the sense that SQL statements that work on statically typed databases should work the same way in SQLite. However, the dynamic typing in SQLite allows it to do things which are not possible in traditional rigidly typed databases.

**Comment by dwf** [comment]
@bartvm says it's no biggie if the column type changes, so let's just merge it as-is. If someone complains, we can figure out what needs to be done at that point. My guess is that this isn't actually being used very much.

**Pull request merged**
