### PR TITLE
Move testing utilities to make them importable from outside

### PR DESCRIPTION
**Pull request by rizar**
I just want to use them for testing in blocks-extras. This PR should be super-easy to review.

### CODE REVIEW

**Comment by rizar** [comment]
The coverage drop is not a big surprise: some of the moved code is not used _inside_ tests, only to wrap them. The scrutinizer crash is mysterious.

**Comment by rizar** [comment]
Tests pass, impatiently waiting for an LGTM.

**Comment by rizar** [comment]
@dwf , @dmitriy-serdyuk , can anybody authorize me to merge this?

**Comment by dmitriy-serdyuk** [comment]
Looks good, but do we want it to be available after setup?

**Comment by rizar** [comment]
What do you mean?

**Comment by dmitriy-serdyuk** [comment]
A user who installed blocks with `setup.py install` doesn't need all these testing utilities in their PYTHONPATH. Maybe it's not a big problem.

**Comment by rizar** [comment]
I am not sure I agree. The whole point here is to make these utilities available as soon as Blocks is installed, so that other packages using Blocks could use them for their tests. So they should be copied to the system (or local) directories upon installation together with the rest of the code.

**Comment by dmitriy-serdyuk** [comment]
Ok, agreed.

**Comment by rizar** [comment]
Is it LGTM?

**Pull request merged**
