### PR TITLE
WIP: Move plotting to blocks-extras

### PR DESCRIPTION
**Pull request by bartvm**
https://github.com/mila-udem/blocks-extras/pull/4

### CODE REVIEW

**Comment by bartvm** [comment]
https://github.com/mila-udem/blocks-examples/pull/6

**Comment by bartvm** [comment]
There's not too much to review here, it's basically moving just files between repos. Would be great if someone could take a quick look so that I can merge it, because it's spread over 3 repos and will be a pain to rebase.

**Comment by bartvm** [comment]
Needs #693.

**Comment by rizar** [comment]
The tests apparently have to be restarted now as #693  is merged.

**Comment by bartvm** [comment]
Nope, tests pass. It's the `blocks-examples` tests that fail, because it's testing the master branch, but https://github.com/mila-udem/blocks-examples/pull/6 will pass, they need to all be merged simultaneously.

**Comment by rizar** [comment]
Go ahead and merge!

**Pull request merged**
