### PR TITLE
change attention.py

### PR DESCRIPTION
**Pull request by wenhuchen**
Change attention score calculation method.

### CODE REVIEW

**Comment by dwf** [comment]
Lots of tests failing, and commit messages like "change <file>" are not useful. We can determine what files are changed by looking at the diff. Commit message should say what the purpose of the change was.

**Comment by rizar** [comment]
An explanation of why you think it is better to multiply than to add would be great.

**Comment by wenhuchen** [comment]
Actually I made this change according to http://www.aclweb.org/anthology/D15-1166, the paper provides three algorithms to calculate the attention. I used the simple dot version and got an increase of about 0.5 BLEU in IWSLT De-En Ted-Talk data set.

**Comment by dwf** [comment]
@wenhuchen Given who wrote it (@rizar), it's probably the case that the method of calculating the attention score currently is already employed in some part of the literature (notably Bahdanau et al, the first paper in the bibliography that manuscript you link). If you'd like to add flags or subclasses in order to make it easy to use the alternate method, that would be great, but simply replacing the score calculation method isn't an option. What works best on one dataset won't necessarily work best for all.

**Comment by wenhuchen** [comment]
Thank you, I will try adding a subclasses and test if it really brings improvement in all dataset.

**Comment by rizar** [comment]
Perhaps the simplest way to add this to Blocks would be to add a flag.
Also, a reference to the paper, where the method originates, would be
required.

**Pull request closed without merging**
