### PR TITLE
Replace uses of named_copy with var.copy(name=...)

### LINKED ISSUE #833: Replace uses of named_copy with var.copy(name=...)
Follow-on to #784. Now that Theano/Theano#3369 was merged, we should get rid of `named_copy`.

### PR DESCRIPTION
**Pull request by yingzha**
Fixes #833

### CODE REVIEW

**Comment by yingzha** [comment]
@dmitriy-serdyuk error comes from mila-udem branch, do I need to make change to that branch or just ignore it?

**Comment by dmitriy-serdyuk** [comment]
It is because of blocks-examples. Can you do replacements in blocks-examples repository as well?

**Comment by dmitriy-serdyuk** [comment]
Waiting for mila-udem/blocks-examples#40

**Comment by dmitriy-serdyuk** [comment]
Ok, this one seems fine as well.

**Comment by dwf** [comment]
@dmitriy-serdyuk you might want to post a message to the mailing list
noting this change and that errors about either named_copy not existing or
var.copy not taking arguments should be resolved by updating blocks,
blocks-examples, and Theano.

**Comment by dmitriy-serdyuk** [comment]
Thanks, I almost forgot about it.

**Pull request merged**
