### PR TITLE
Remove ConvolutionalActivation.

### LINKED ISSUE #971: ConvolutionalActivation is no longer necessary
#968 adds a few lines which obviate the need for ConvolutionalActivation to exist at all.

I propose we get rid of it.

### PR DESCRIPTION
**Pull request by dwf**
Fixes #971.

Probably best to save until after the ICML deadline.

### CODE REVIEW

**Comment by dwf** [comment]
examples will of course have to be updated in parallel if this PR is accepted.

**Comment by dwf** [comment]
@thrandis @bartvm @memimo @vdumoulin thoughts on this one?

**Comment by bartvm** [comment]
LGTM

**Comment by vdumoulin** [comment]
LGTM as well.

**Pull request merged**
