### PR TITLE
WIP: New bricks

### PR DESCRIPTION
**Pull request by bartvm**
WIP, but this is basically a rewrite of `blocks/bricks/base.py`. It implements the `lazy` decorator as discussed in https://github.com/bartvm/blocks/issues/337#issuecomment-75884106 with @rizar and @fvisin. It also ditches metaclasses in favor of class decorators; I need to confirm later on that these actually pickle well, but my initial tests seem to show they do.

Currently it's still very messy, but it cuts 20% of the lines `base.py`. There are a few functionalities which took acrobatics to support, which I'm not sure are actually used, so I would propose removing them if at all possible. Notably, the ability to set the attributes of applications i.e. to do `brick.apply.inputs = ['x']`. This is annoying because it prevents us from actually turning `brick.apply.inputs` in a bound method (it's impossible to set an attribute of an `instancemethod`).

This also switches to using decorators for `allocation`, `initialization`, etc. as suggested in https://github.com/bartvm/blocks/issues/39. Expecting a user to override private methods is pretty bad form I think, so we need to either change the name of the method to something without a leading underscore, or use decorators. I went with decorators for now, because otherwise it's confusing for users to implement one method, but call another.

### CODE REVIEW

**Comment by bartvm** [comment]
@fvisin If you want to help make your idea work, please help me update all the bricks to use the new `lazy` decorator :) They should all look like:

```python
@lazy(allocation=['args', 'needed', 'for', 'allocation'],
      initialization=['likewise'])
def __init__(self, always_needed, args, needed, for allocation,
             likewise, allocation_var_with_default=None):
    pass
```

**Comment by fvisin** [comment]
Nice job Bart!
I will look into it as soon as I have some spare time and I will work on the decorators too. Probably not before Thursday though.

**Comment by rizar** [comment]
I really respect you Bart for your ability to work on several huge PRs at the same time, but this exceeds my reviewing capabilities. Can we finish with log refactoring first?

**Comment by bartvm** [comment]
There's not much point in reviewing this right now anyway, it's too much WIP. Currently running into the same pickling issues, but trying to come up with a cleaner solution this time. I'll let people know if/when I get it into a working state.

The database backend is indeed important, but the problem I ran into is quite fundamental, and needs a bit of thinking and/or some good suggestions.

**Pull request closed without merging**
