### PR TITLE
Catch any exception on old backend import

### PR DESCRIPTION
**Pull request by dmitriy-serdyuk**
Theano 9.0 crashes when trying to import the old backend.

### CODE REVIEW

**Comment by dmitriy-serdyuk** [comment]
@rizar, this is an important one.

**Comment by rizar** [comment]
Can you please change to "except Exception" in order not to catch `KeyboardInterrupt` and other stuff like that? 

https://stackoverflow.com/questions/730764/try-except-in-python-how-do-you-properly-ignore-exceptions

After that, LGTM

**Comment by dmitriy-serdyuk** [comment]
I wanted to say that `KeyboardInterrupt` never happens in import section, but considering the slowness of import of theano sometimes... I'll change it.

**Comment by rizar** [comment]
That's precisely how I reasoned about it :)

**Pull request merged**
