### PR TITLE
Pass kwargs to unpickler.

### PR DESCRIPTION
**Pull request by dwf**
It's already done for dumping.

### CODE REVIEW

**Comment by dmitriy-serdyuk** [comment]
> Python pickles

Python terminology is so funny..

Pickles

**Comment by dmitriy-serdyuk** [comment]
Any ideas why Travis wasn't run?

**Comment by dwf** [comment]
None. WTF Travis.

**Comment by dwf** [comment]
And Scrutinizer is its usual useless self.

**Comment by dwf** [comment]
#1091 seemed to trigger it.

**Pull request closed without merging**
