### PR TITLE
Add links to the code in docs

### PR DESCRIPTION
**Pull request by dmitriy-serdyuk**
Borrowed this piece of code from numpy and modified the library name.

It works when I build it locally.

### CODE REVIEW

**Comment by dmitriy-serdyuk** [comment]
This code is mostly copy-paste of [this](https://github.com/numpy/numpy/blob/master/doc/source/conf.py#L286) function in numpy. It creates a link to a corresponding file, line number at github using inspection mechanisms.

**Comment by rizar** [comment]
But I don't understand where and by whom this `linkcode_resolve` is called.

**Comment by dmitriy-serdyuk** [comment]
It is called by `sphinx.ext.linkcode` sphinx [module](http://www.sphinx-doc.org/en/stable/ext/linkcode.html) every time it creates a documentation item for a class/function/etc. `info` argument is a dictionary which contains module name, full path and maybe other stuff which is not very well documented. 

Here, I'm using the path to get inspection information: full name and line number where it is defined in a file.

**Comment by rizar** [comment]
OK, I see. Nice new feature for our docs! If it works for you locally, I do not mind merging.

**Comment by dmitriy-serdyuk** [comment]
Let's try, I'll check read the docs.

**Comment by dmitriy-serdyuk** [comment]
Cool, it works!

**Pull request merged**
