### PR TITLE
Fix serialization with protocol 0 on Python 3.

### PR DESCRIPTION
**Pull request by dwf**
Not sure why this was happening but this is a simple fix.

### CODE REVIEW

**Comment by dwf** [comment]
@rizar 

```
wardefar@leto14:~/src/blocks$ nosetests tests/test_serialization.py:test_protocol0_regression
F
======================================================================
FAIL: Check for a regression where protocol 0 dumps fail on load.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/wardefar/src/blocks/tests/test_serialization.py", line 172, in test_protocol0_regression
    load(buf)
  File "/u/wardefar/src/blocks/blocks/serialization.py", line 270, in load
    return p.load()
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/wardefar/miniconda/envs/invert/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/u/wardefar/src/blocks/tests/test_serialization.py", line 174, in test_protocol0_regression
    assert False  # Regression
AssertionError

----------------------------------------------------------------------
Ran 1 test in 0.092s

FAILED (failures=1)
wardefar@leto14:~/src/blocks$ git checkout fix_serialization_protocol0
M       blocks/extensions/monitoring.py
M       blocks/monitoring/evaluators.py
M       tests/test_serialization.py
Previous HEAD position was 41dd4af... Merge pull request #1075 from mila-udem/override_sharedvariablemodifier
Switched to branch 'fix_serialization_protocol0'
wardefar@leto14:~/src/blocks$ nosetests tests/test_serialization.py:test_protocol0_regression
.
----------------------------------------------------------------------
Ran 1 test in 0.071s

OK
```

**Comment by dwf** [comment]
Waiting to make sure test passes on Python 2.

**Comment by dwf** [comment]
And we're passed. Do I have the LGTM?

**Comment by rizar** [comment]
Sure, thanks!

**Pull request merged**
