### PR TITLE
Add cache in _PersistentLoad

### LINKED ISSUE #1031: load() not working on brand new checkpoint
Hitting a Theano assertion. Anyone seen this before?

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-6-f65624dca9da> in <module>()
      2 for c in checkpoints:
      3     with open(c, 'rb') as f:
----> 4         loops.append(load(f))

/u/wardefar/src/blocks/blocks/serialization.py in load(file_, name, use_cpickle)
    259         if '_parameters' in tar_file.getnames():
    260             p.persistent_load = _PersistentLoad(tar_file)
--> 261         return p.load()
    262 
    263 

/u/wardefar/src/theano/theano/compile/function_module.py in _constructor_Function(maker, input_storage, inputs_data)
   1026         assert (container.data is x) or \
   1027             (isinstance(x, numpy.ndarray) and (container.data == x).all()) or \
-> 1028             (container.data == x)
   1029     return f
   1030 

AssertionError: 
```

### PR DESCRIPTION
**Pull request by rizar**
Fixes #1031

### CODE REVIEW

**Comment by rizar** [comment]
Also fixes https://github.com/Theano/Theano/issues/4238

**Comment by dwf** [comment]
Works on both the examples I tried (one from blocks-examples, one from my weight normalization mini-experiment this morning)

LGTM, merging.

**Comment by dwf** [comment]
Or I guess merging when the CI build passes.

**Comment by dwf** [comment]
Okay, Coveralls is being stupid but Travis passed so I'll merge.

Thanks for the help in hunting this down!

**Pull request merged**
