### PR TITLE
Make TrackTheBest default to after_epoch.

### LINKED ISSUE #684: TrackTheBest should default to after_epoch?
Monitoring is only done after every epoch (by default), so there's no sense in invoking TrackTheBest it after every batch (by default). Is that logic right @rizar?

### PR DESCRIPTION
**Pull request by dwf**
Fixes #684.

@rizar

### CODE REVIEW

**Comment by rizar** [comment]
Looks sooooo good to me!

**Comment by dwf** [comment]
Think I will need to fix the test :)

**Comment by dwf** [comment]
Alright, @rizar, PTAL. Travis finished but Coveralls is missing in action.

**Comment by rizar** [comment]
Coverage is very confused, but we know that this PR shouldn't make it less, don't we?

**Pull request merged**
